# Generated by Django 3.0.14 on 2024-04-17 08:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vs_app', '0002_auto_20240417_1109'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productionlog',
            name='duration',
            field=models.DecimalField(decimal_places=2, max_digits=5),
        ),
    ]
